CREATE DATABASE shop_db;
USE shop_db;

CREATE TABLE T17_DEPARTMENT (
    C17_DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    C17_DEPARTMENT_NAME VARCHAR(100)
);

CREATE TABLE T20_ROLE (
    C20_ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C20_ROLE_NAME VARCHAR(100)
);

CREATE TABLE T07_ITEM_GROUP (
    C07_ITEM_GROUP_ID INT AUTO_INCREMENT PRIMARY KEY,
    C07_ITEM_GROUP_NAME VARCHAR(100),
    C07_STATUS VARCHAR(50)
);

CREATE TABLE T06_PROVIDER (
    C06_PROVIDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    C06_PROVIDER_NAME VARCHAR(100),
    C06_PROVIDER_TAX VARCHAR(50)
);

CREATE TABLE T11_PAYMENT_METHOD (
    C11_PAYMENT_METHOD_ID INT AUTO_INCREMENT PRIMARY KEY,
    C11_PAYMENT_METHOD_NAME VARCHAR(100)
);

CREATE TABLE T13_ORDER_STATUS (
    C13_ORDER_STATUS_ID INT AUTO_INCREMENT PRIMARY KEY,
    C13_ORDER_STATUS_DESC VARCHAR(100)
);

CREATE TABLE T22_TAX (
    C22_TAX_ID INT AUTO_INCREMENT PRIMARY KEY,
    C22_TAX_IN_PERCENT DECIMAL(5,2),
    C22_TOTAL_OF_MONEY DECIMAL(15,2),
    C22_DATE_SUBMIT DATE,
    C22_DATE_FROM DATE,
    C22_DATE_UNTIL DATE,
    C22_TAX_PAYER_ID VARCHAR(50)
);

CREATE TABLE T19_VOUCHER (
    C19_VOUCHER_ID INT AUTO_INCREMENT PRIMARY KEY,
    C19_REDUCING_MONEY DECIMAL(15,2),
    C19_REDUCING_IN_PERCENT DECIMAL(5,2),
    C19_DATE_START DATE,
    C19_DATE_END DATE,
    C19_VOUCHER_STATUS VARCHAR(50)
);

CREATE TABLE T02_SIZE (
    C02_SIZE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C02_SIZE_NAME VARCHAR(50),
    C02_GENDER TINYINT,
    C02_SIZE_DESC VARCHAR(100),
    UNIQUE (C02_SIZE_NAME, C02_GENDER)
);

CREATE TABLE T16_EMPLOYEE (
    C16_EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C16_EMPLOYEE_NAME VARCHAR(100),
    C16_EMPLOYEE_EMAIL VARCHAR(100),
    C16_EMPLOYEE_ADDRESS VARCHAR(255),
    C16_EMPLOYEE_PHONE VARCHAR(20),
    C16_EMPLOYEE_PASSWORD VARCHAR(255),
    C16_GMAIL_TOKEN VARCHAR(255),
    C16_DEPARTMENT_ID INT,
    FOREIGN KEY (C16_DEPARTMENT_ID) REFERENCES T17_DEPARTMENT(C17_DEPARTMENT_ID)
);

CREATE TABLE T15_CUSTOMER (
    C15_CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    C15_CUSTOMER_NAME VARCHAR(100),
    C15_CUSTOMER_EMAIL VARCHAR(100),
    C15_CUSTOMER_ADDRESS VARCHAR(255),
    C15_CUSTOMER_PHONE VARCHAR(20),
    C15_CUSTOMER_PASSWORD VARCHAR(255),
    C15_GMAIL_TOKEN VARCHAR(255)
);

CREATE TABLE T01_ITEM (
    C01_ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    C01_ITEM_NAME VARCHAR(100),
    C01_ITEM_GROUP_ID INT,
    C01_COLOR VARCHAR(50),
    FOREIGN KEY (C01_ITEM_GROUP_ID) REFERENCES T07_ITEM_GROUP(C07_ITEM_GROUP_ID)
);

CREATE TABLE T21_ROLE_DETAIL (
    C21_EMPLOYEE_ID INT,
    C21_ROLE INT,
    PRIMARY KEY (C21_EMPLOYEE_ID, C21_ROLE),
    FOREIGN KEY (C21_EMPLOYEE_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID),
    FOREIGN KEY (C21_ROLE) REFERENCES T20_ROLE(C20_ROLE_ID)
);

CREATE TABLE T03_ITEM_DETAIL (
    C03_ITEM_ID INT,
    C03_SIZE_ID INT,
    C03_SALES_PRICE DECIMAL(15,2),
    C03_AMOUNT INT,
    PRIMARY KEY (C03_ITEM_ID, C03_SIZE_ID),
    FOREIGN KEY (C03_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID),
    FOREIGN KEY (C03_SIZE_ID) REFERENCES T02_SIZE(C02_SIZE_ID)
);

CREATE TABLE T18_DELIVERY_ADDRESS (
    C18_DELIVERY_ADDRESS_ID INT AUTO_INCREMENT PRIMARY KEY,
    C18_CUSTOMER_ID INT,
    C18_RECEIVER_NAME VARCHAR(100),
    C18_ADDRESS VARCHAR(255),
    FOREIGN KEY (C18_CUSTOMER_ID) REFERENCES T15_CUSTOMER(C15_CUSTOMER_ID)
);

CREATE TABLE T04_WAREHOUSE_RECEIPT (
    C04_WHRECEIPT_ID INT AUTO_INCREMENT PRIMARY KEY,
    C04_WHRECEIPT_TIME DATETIME,
    C04_EMPLOYEE_ID INT,
    FOREIGN KEY (C04_EMPLOYEE_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID)
);

CREATE TABLE T05_WAREHOUSE_RECEIPT_DETAIL (
    C05_WHRECEIPT_ID INT,
    C05_ITEM_ID INT,
    C05_AMOUNT INT,
    C05_BUY_PRICE DECIMAL(15,2),
    C05_PROVIDER_ID INT,
    PRIMARY KEY (C05_WHRECEIPT_ID, C05_ITEM_ID),
    FOREIGN KEY (C05_WHRECEIPT_ID) REFERENCES T04_WAREHOUSE_RECEIPT(C04_WHRECEIPT_ID),
    FOREIGN KEY (C05_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID),
    FOREIGN KEY (C05_PROVIDER_ID) REFERENCES T06_PROVIDER(C06_PROVIDER_ID)
);

CREATE TABLE T08_GALLERY (
    C08_IMAGE_PATH VARCHAR(255) PRIMARY KEY,
    C08_ITEM_ID INT,
    FOREIGN KEY (C08_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);

CREATE TABLE T23_CART (
    C23_CART_ID INT AUTO_INCREMENT PRIMARY KEY,
    C23_CUSTOMER_ID INT,
    C23_DATE_CREATED DATETIME,
    FOREIGN KEY (C23_CUSTOMER_ID) REFERENCES T15_CUSTOMER(C15_CUSTOMER_ID)
);

CREATE TABLE T09_ORDER (
    C09_ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    C09_ORDER_TIME DATETIME,
    C09_PAYMENT_METHOD_ID INT,
    C09_CUSTOMER_ID INT,
    C09_DELIVERY_ADDRESS_ID INT,
    C09_EMPLOYEE_ID INT,
    FOREIGN KEY (C09_PAYMENT_METHOD_ID) REFERENCES T11_PAYMENT_METHOD(C11_PAYMENT_METHOD_ID),
    FOREIGN KEY (C09_CUSTOMER_ID) REFERENCES T15_CUSTOMER(C15_CUSTOMER_ID),
    FOREIGN KEY (C09_DELIVERY_ADDRESS_ID) REFERENCES T18_DELIVERY_ADDRESS(C18_DELIVERY_ADDRESS_ID),
    FOREIGN KEY (C09_EMPLOYEE_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID)
);

CREATE TABLE T10_BILL (
    C10_BILL_ID INT AUTO_INCREMENT PRIMARY KEY,
    C10_ORDER_ID INT,
    C10_DELIVERY_FEE DECIMAL(15,2),
    C10_VOUCHER_ID INT,
    C10_TOTAL_OF_MONEY DECIMAL(15,2),
    FOREIGN KEY (C10_ORDER_ID) REFERENCES T09_ORDER(C09_ORDER_ID),
    FOREIGN KEY (C10_VOUCHER_ID) REFERENCES T19_VOUCHER(C19_VOUCHER_ID)
);

CREATE TABLE T12_ORDER_DETAIL (
    C12_ORDER_ID INT,
    C12_ITEM_ID INT,
    C12_AMOUNT INT,
    PRIMARY KEY (C12_ORDER_ID, C12_ITEM_ID),
    FOREIGN KEY (C12_ORDER_ID) REFERENCES T09_ORDER(C09_ORDER_ID),
    FOREIGN KEY (C12_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);

CREATE TABLE T14_ORDER_STATUS_DETAIL (
    C14_ORDER_ID INT,
    C14_ORDER_STATUS_ID INT,
    C14_EMPLOYEE_ID INT,
    C14_LAST_UPDATED DATETIME,
    PRIMARY KEY (C14_ORDER_ID, C14_ORDER_STATUS_ID),
    FOREIGN KEY (C14_ORDER_ID) REFERENCES T09_ORDER(C09_ORDER_ID),
    FOREIGN KEY (C14_ORDER_STATUS_ID) REFERENCES T13_ORDER_STATUS(C13_ORDER_STATUS_ID),
    FOREIGN KEY (C14_EMPLOYEE_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID)
);

CREATE TABLE T23_SHOPPING_CART (
    C23_CART_ID INT,
    C23_ITEM_ID INT,
    C23_AMOUNT INT,
    C23_DATE_ADDING DATETIME,
    C23_DATE_REMOVING DATETIME,
    PRIMARY KEY (C23_CART_ID, C23_ITEM_ID),
    FOREIGN KEY (C23_CART_ID) REFERENCES T23_CART(C23_CART_ID),
    FOREIGN KEY (C23_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);

CREATE TABLE T24_CART_LATER_ON (
    C24_CUSTOMER_ID INT,
    C24_ITEM_ID INT,
    C24_AMOUNT INT,
    PRIMARY KEY (C24_CUSTOMER_ID, C24_ITEM_ID),
    FOREIGN KEY (C24_CUSTOMER_ID) REFERENCES T15_CUSTOMER(C15_CUSTOMER_ID),
    FOREIGN KEY (C24_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);